### PR TITLE
Had to be done.

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by pa9ey** [comment]
Hey, @AlexKent3141!

**Comment by mbreckon** [comment]
Feel free to do a more wide ranging code review or submit other patches. I'm hoping the code is reasonably clear at the moment but...

**Comment by pa9ey** [comment]
Absolutely! I'm off in search of `var flb = new FrinkinLaserBeam()`...

**Comment by mbreckon** [comment]
See the README - no frickin lasers yet :-(

**Comment by AlexKent3141** [comment]
Glad that this critical patch made it in :)

This looks like a good start - it will be interesting to see how you deal with move generation + lasers with this piece-centric design!

**Comment by mbreckon** [comment]
It does generate moves for Anubis - just not the rest. I've also created an experimental branch to take it in an even more extreme direction where there isn't even a board.

**Comment by mbreckon** [comment]
strictly it isn't true that there won't be a board... but it probably won't know where the pieces are...

**Pull request merged**
